"""Build the NSW CTP severity causal DAG.

Emits ``causal/ctp_causal_dag.json`` — the machine-readable structure consumed by
the causal (DAG-aware) TabPFN generator described in
``specs/nsw-ctp-causative.md``.

PROVENANCE — READ THIS BEFORE RELYING ON THE GRAPH.
The edge list, the signs, the strengths and the mechanism strings below were
**generated by a large language model** (Claude) from its training knowledge of
NSW CTP scheme mechanics (Motor Accident Injuries Act 2017 / Motor Accidents
Compensation Act 1999 heads of damage).  **No lawyer, actuary or claims
practitioner has reviewed any edge.**  Earlier versions of this file described
the graph as "expert-elicited"; that was inaccurate and has been corrected.

The graph is then **annotated** with the empirical association each edge carries
in ``ctp/ctp.csv``.  The associations do not orient the edges, and they cannot
validate them — a plausible-sounding wrong arrow will still carry a correlation.
They are reported so a reader can see which asserted mechanisms the data is at
least consistent with.

The descriptive statistics quoted inside the ``note`` and ``mechanism`` strings
are checked against the CSV by ``causal/verify_claims.py``.  The causal
assertions themselves are unverified and unfalsifiable from 540 observational
rows; they need domain review.

Run:  python causal/build_ctp_causal_dag.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "ctp" / "ctp.csv"
OUT = Path(__file__).resolve().parent / "ctp_causal_dag.json"

# --------------------------------------------------------------------------
# Bands: the causal-temporal layers of a CTP claim.  Every edge runs from a
# lower band to the same or a higher band; never backwards.
# --------------------------------------------------------------------------
BANDS = [
    {
        "id": "claimant",
        "label": "Claimant, pre-accident",
        "blurb": "Fixed before the accident. Nothing downstream can change these.",
    },
    {
        "id": "injury",
        "label": "Accident & injury",
        "blurb": "The crash and the harm it caused. Liability is a fact of the accident, not of the claimant.",
    },
    {
        "id": "clinical",
        "label": "Clinical course & capacity",
        "blurb": "How the injury played out: treatment, permanent impairment, ability to work.",
    },
    {
        "id": "dispute",
        "label": "Dispute & forum",
        "blurb": "What ends up contested, and whether the claim resolves by settlement approval or a damages assessment.",
    },
    {
        "id": "heads",
        "label": "Heads of damage",
        "blurb": "The two quantum components the decision actually records.",
    },
    {
        "id": "award",
        "label": "Award",
        "blurb": "The total. A pure sink — it causes nothing.",
    },
]

# --------------------------------------------------------------------------
# Nodes.  x/y are dashboard layout coordinates (SVG user units).
# --------------------------------------------------------------------------
NODES = [
    # -- claimant ----------------------------------------------------------
    dict(id="Claimant Age", short="Age", band="claimant", kind="numeric",
         x=118, y=130,
         note="Age at injury. Root: nothing in the claim can cause it."),
    dict(id="Claimant Gender", short="Gender", band="claimant", kind="categorical",
         x=118, y=248,
         note="Root. Enters mainly through pre-accident earnings and occupation mix."),
    dict(id="Claimant Weekly Income", short="Weekly income", band="claimant", kind="numeric",
         x=118, y=366,
         note="Pre-accident earnings — the multiplicand for economic loss. 41.9% missing, "
              "and the missingness is itself informative (not working / not in evidence)."),
    dict(id="Pre-existing Condition Salience", short="Pre-existing", band="claimant", kind="ordinal",
         x=118, y=506,
         note="How prominent a prior condition is in the decision. Degenerative change "
              "accumulates with age, so Age is its parent."),
    # -- injury ------------------------------------------------------------
    dict(id="Injury Burden Intensity", short="Injury burden", band="injury", kind="ordinal",
         x=352, y=110,
         note="Overall physical burden of the injuries (0–4). The accident forces that "
              "produced it are unobserved — treated as exogenous noise."),
    dict(id="Psychological Injury Emphasis", short="Psych emphasis", band="injury", kind="ordinal",
         x=352, y=300,
         note="Weight the decision gives to psychological injury (0–2)."),
    dict(id="Liability Clarity", short="Liability clarity", band="injury", kind="ordinal",
         x=352, y=618,
         note="How clear fault is (0–2). A fact of the accident. Near-constant here "
              "(91.9% at the top level) — a weak but genuinely exogenous discount lever."),
    # -- clinical ----------------------------------------------------------
    dict(id="WPI %", short="WPI %", band="clinical", kind="numeric",
         x=586, y=92,
         note="Whole Person Impairment from the medical assessment. The statutory gate for "
              "non-economic loss (>10%). 46.9% missing — recorded only when it was assessed."),
    dict(id="Treatment Burden", short="Treatment burden", band="clinical", kind="ordinal",
         x=586, y=210,
         note="Extent of treatment / surgery / ongoing care (0–3)."),
    dict(id="Work Impact Severity", short="Work impact", band="clinical", kind="ordinal",
         x=586, y=372,
         note="Loss of working capacity (0–3). The driver of economic loss."),
    # -- dispute -----------------------------------------------------------
    dict(id="Causation Complexity", short="Causation", band="dispute", kind="ordinal",
         x=820, y=478,
         note="How hard it is to attribute the condition to the accident (0–2). "
              "Pre-existing conditions and psychological claims are what make it hard."),
    dict(id="Nature", short="Nature (forum)", band="dispute", kind="categorical",
         x=820, y=596,
         note="Settlement Approval vs Damages. An effect of how contested the claim is, "
              "not a cause of the injury. Damages matters run 2.6x the median award — "
              "almost all of that is confounding by severity, not the forum itself."),
    dict(id="Legal Procedural Complexity", short="Legal complexity", band="dispute", kind="ordinal",
         x=820, y=700,
         note="Procedural complexity of the proceeding (0–3). A leaf: it records the "
              "dispute, it does not set quantum."),
    # -- heads -------------------------------------------------------------
    dict(id="Non-Economic Loss", short="Non-economic loss", band="heads", kind="numeric",
         x=1054, y=150,
         note="General damages for pain and suffering. Gated on WPI > 10%: 77% of awards "
              "at or below 10% WPI are exactly $0. 15.4% missing."),
    dict(id="Future Economic Loss", short="Future economic loss", band="heads", kind="numeric",
         x=1054, y=360,
         note="Future loss of earning capacity: weekly income x lost capacity x years to "
              "retirement. 23.5% missing."),
    # -- award -------------------------------------------------------------
    dict(id="Lump Sum", short="Lump Sum", band="award", kind="numeric",
         x=1274, y=248,
         note="TARGET. The total award: the two recorded heads plus past economic loss, "
              "treatment and care. A collider — and column 0 of the CSV."),
]

# --------------------------------------------------------------------------
# Edges.  sign: '+' | '-' | '~' (context-dependent / non-monotone).
# strength: prior confidence in the mechanism, not the measured association.
# --------------------------------------------------------------------------
EDGES = [
    # claimant internals
    ("Claimant Age", "Claimant Weekly Income", "+", "high",
     "Age-earnings profile: earnings rise then plateau and fall at retirement."),
    ("Claimant Gender", "Claimant Weekly Income", "+", "high",
     "Gendered occupation mix and hours. Contrast is Male vs Female: male claimants' median "
     "weekly income is 29% higher."),
    ("Claimant Age", "Pre-existing Condition Salience", "+", "high",
     "Degenerative change accumulates, so older claimants arrive with more prior pathology on the record."),
    # injury layer
    ("Claimant Age", "Injury Burden Intensity", "+", "medium",
     "Frailty: the same collision produces more burden (fractures, slower union) in older claimants."),
    ("Injury Burden Intensity", "Psychological Injury Emphasis", "+", "high",
     "More severe physical injury produces more secondary psychological injury."),
    ("Claimant Age", "Psychological Injury Emphasis", "-", "medium",
     "Psychological components are pleaded and emphasised more for working-age claimants."),
    ("Pre-existing Condition Salience", "Psychological Injury Emphasis", "+", "medium",
     "Prior psychological or chronic-pain history raises the psychological emphasis."),
    # clinical layer
    ("Injury Burden Intensity", "Treatment Burden", "+", "high",
     "More severe injuries need more surgery, rehabilitation and ongoing care."),
    ("Psychological Injury Emphasis", "Treatment Burden", "+", "medium",
     "Psychological injury adds a treatment stream of its own."),
    ("Injury Burden Intensity", "WPI %", "+", "high",
     "WPI is the assessor's measurement of exactly this burden."),
    ("Treatment Burden", "WPI %", "+", "medium",
     "Surgical intervention and failure to resolve push the assessed impairment up."),
    ("Psychological Injury Emphasis", "WPI %", "+", "medium",
     "Psychiatric impairment is separately assessable and adds to the recorded figure."),
    ("Pre-existing Condition Salience", "WPI %", "-", "high",
     "Statutory deduction: the proportion of impairment attributable to a prior condition is subtracted."),
    ("Claimant Age", "WPI %", "+", "low",
     "Age-related degeneration raises measured impairment before deduction."),
    ("Injury Burden Intensity", "Work Impact Severity", "+", "high",
     "Physical burden limits what work the claimant can still do."),
    ("Psychological Injury Emphasis", "Work Impact Severity", "+", "high",
     "Psychological injury is a major driver of incapacity independent of physical burden."),
    ("Treatment Burden", "Work Impact Severity", "+", "medium",
     "A long treatment course keeps the claimant off work."),
    ("Claimant Age", "Work Impact Severity", "-", "high",
     "Claimants at or past retirement have little working capacity left to lose."),
    ("Claimant Gender", "Work Impact Severity", "+", "low",
     "Occupation mix: manual roles lose capacity faster than sedentary ones. Contrast is "
     "Male vs Female."),
    # dispute layer
    ("Pre-existing Condition Salience", "Causation Complexity", "+", "high",
     "The single biggest source of causation argument is a prior condition to apportion against."),
    ("Psychological Injury Emphasis", "Causation Complexity", "+", "high",
     "Psychological injury is the most-contested causal link in the scheme."),
    ("Causation Complexity", "Nature", "+", "high",
     "Contested causation is what pushes a claim out of settlement approval into a damages assessment."),
    ("Liability Clarity", "Nature", "-", "medium",
     "Clear fault settles; disputed fault is assessed."),
    ("Work Impact Severity", "Nature", "+", "medium",
     "Large economic-loss claims are worth litigating."),
    ("Claimant Age", "Nature", "-", "medium",
     "Younger claimants have the future-earnings exposure that justifies a damages assessment."),
    ("Causation Complexity", "Legal Procedural Complexity", "+", "high",
     "Causation disputes generate the medical evidence, joinder and interlocutory steps that are recorded here."),
    ("Nature", "Legal Procedural Complexity", "+", "high",
     "A damages assessment is procedurally heavier than approving an agreed settlement."),
    ("Psychological Injury Emphasis", "Legal Procedural Complexity", "+", "medium",
     "Psychiatric evidence multiplies the assessments and the argument."),
    ("Work Impact Severity", "Legal Procedural Complexity", "+", "medium",
     "Contested capacity means vocational and economic evidence."),
    ("Liability Clarity", "Legal Procedural Complexity", "-", "low",
     "Clear liability removes a whole limb of the argument."),
    # heads of damage
    ("WPI %", "Non-Economic Loss", "+", "high",
     "STATUTORY GATE. No non-economic loss below the >10% WPI threshold; above it, quantum "
     "scales with the assessed impairment."),
    ("Injury Burden Intensity", "Non-Economic Loss", "+", "high",
     "Pain and suffering track the burden itself, beyond the impairment percentage."),
    ("Psychological Injury Emphasis", "Non-Economic Loss", "+", "medium",
     "Psychological sequelae add to general damages where the threshold is met."),
    ("Liability Clarity", "Non-Economic Loss", "+", "medium",
     "Contributory negligence discounts the award proportionally."),
    ("Causation Complexity", "Non-Economic Loss", "-", "medium",
     "Apportionment against non-accident causes reduces the recoverable component."),
    ("Claimant Age", "Non-Economic Loss", "-", "low",
     "Shorter remaining life over which to suffer the loss."),
    ("Work Impact Severity", "Future Economic Loss", "+", "high",
     "The residual-capacity discount is the core of the calculation."),
    ("Claimant Weekly Income", "Future Economic Loss", "+", "high",
     "The multiplicand: future loss is lost weekly earnings x the multiplier."),
    ("Claimant Age", "Future Economic Loss", "-", "high",
     "The multiplier: fewer years to retirement means fewer years of loss."),
    ("WPI %", "Future Economic Loss", "+", "medium",
     "Permanent impairment corroborates permanent loss of capacity."),
    ("Liability Clarity", "Future Economic Loss", "+", "medium",
     "Contributory negligence discounts this head too."),
    ("Causation Complexity", "Future Economic Loss", "-", "medium",
     "Loss attributable to a pre-existing condition is carved out."),
    ("Nature", "Future Economic Loss", "+", "low",
     "Damages assessments reach the fully-argued figure; approved settlements are compromised."),
    # award
    ("Non-Economic Loss", "Lump Sum", "+", "high",
     "ARITHMETIC. A recorded component of the total."),
    ("Future Economic Loss", "Lump Sum", "+", "high",
     "ARITHMETIC. A recorded component of the total."),
    ("Claimant Weekly Income", "Lump Sum", "+", "medium",
     "Past economic loss — a head of damage the table does not record separately."),
    ("Work Impact Severity", "Lump Sum", "+", "medium",
     "Past economic loss and future care both scale with lost capacity."),
    ("Treatment Burden", "Lump Sum", "+", "medium",
     "Medical, care and domestic-assistance heads the table does not record separately."),
    ("Liability Clarity", "Lump Sum", "+", "low",
     "The contributory-negligence discount applies to the whole award."),
]

# --------------------------------------------------------------------------
# Missingness sub-graph (an m-graph: R_v = 1 when v is *not* recorded).
# These are NOT columns of ctp.csv; the generator materialises them.
# --------------------------------------------------------------------------
MISSING_NODES = [
    dict(id="R_WPI", target="WPI %", rate=0.469,
         note="WPI is written down only when an impairment assessment was in evidence."),
    dict(id="R_Income", target="Claimant Weekly Income", rate=0.419,
         note="Weekly income appears only where earnings were in issue and proved."),
    dict(id="R_FEL", target="Future Economic Loss", rate=0.235,
         note="Future economic loss is stated only when it was claimed and quantified."),
    dict(id="R_NEL", target="Non-Economic Loss", rate=0.154,
         note="Non-economic loss is stated only when the threshold question was reached."),
    dict(id="R_Age", target="Claimant Age", rate=0.081,
         note="Age is occasionally not extractable from the decision."),
]

MISSING_EDGES = [
    ("WPI %", "R_WPI", "-", "SELF-MASKING. Assessment is sought when the >10% threshold is live, "
                            "so a recorded WPI is not missing at random in WPI itself."),
    ("Injury Burden Intensity", "R_WPI", "-", "Minor injuries never reach an assessment."),
    ("Nature", "R_WPI", "-", "Damages assessments turn on the threshold; 42.0% missing vs 49.4% "
                             "in settlement approvals."),
    ("WPI %", "R_NEL", "+", "Below the threshold the head is simply not addressed: 18.4% missing "
                            "at WPI<=10 against 3.0% above it."),
    ("Nature", "R_NEL", "-", "A damages assessment must deal with every pleaded head."),
    ("Work Impact Severity", "R_Income", "-", "Earnings are proved when capacity is in issue."),
    ("Claimant Gender", "R_Income", "+", "47.7% missing for female claimants vs 37.2% for male — "
                                         "an evidentiary artefact worth preserving."),
    ("Claimant Age", "R_Income", "+", "Retired claimants have no earnings to record."),
    ("R_Income", "R_FEL", "+", "SHARED MECHANISM. 50.4% of rows missing income are also missing "
                               "future economic loss, against 4.1% of rows with income."),
    ("Work Impact Severity", "R_FEL", "-", "No lost capacity, no future economic loss claim."),
    ("Nature", "R_FEL", "-", "A damages assessment quantifies the head explicitly."),
    ("Nature", "R_Age", "-", "Damages decisions set out the claimant's circumstances in more detail."),
]


# --------------------------------------------------------------------------
def topological_order(nodes, edges):
    """Kahn's algorithm; ties broken by band then declaration order (stable)."""
    order_hint = {n["id"]: i for i, n in enumerate(nodes)}
    parents = {n["id"]: set() for n in nodes}
    children = {n["id"]: set() for n in nodes}
    for src, dst, *_ in edges:
        parents[dst].add(src)
        children[src].add(dst)

    remaining = dict((k, set(v)) for k, v in parents.items())
    out = []
    while remaining:
        ready = sorted([k for k, v in remaining.items() if not v], key=lambda k: order_hint[k])
        if not ready:
            raise ValueError(f"cycle detected among {sorted(remaining)}")
        for k in ready:
            out.append(k)
            del remaining[k]
        for v in remaining.values():
            v.difference_update(ready)
    return out


def spearman(df, a, b):
    """Pairwise-complete Spearman, on log1p for the heavy-tailed dollar columns."""
    heavy = {"Lump Sum", "Non-Economic Loss", "Future Economic Loss", "Claimant Weekly Income"}
    s = df[[a, b]].dropna().copy()
    if len(s) < 30:
        return None, len(s)
    for name in (a, b):
        if name in heavy:
            s[name] = np.log1p(s[name])
    if s[a].nunique() < 2 or s[b].nunique() < 2:
        return None, len(s)
    return float(stats.spearmanr(s[a], s[b]).statistic), len(s)


def main():
    df = pd.read_csv(CSV)
    # numeric codes for the two string columns so associations are computable
    num = df.copy()
    num["Claimant Gender"] = (num["Claimant Gender"] == "Male").astype(int)
    num["Nature"] = (num["Nature"] == "Damages").astype(int)

    order = topological_order(NODES, EDGES)
    rank = {n: i for i, n in enumerate(order)}
    for src, dst, *_ in EDGES:
        assert rank[src] < rank[dst], f"back-edge {src} -> {dst}"

    csv_order = list(df.columns)
    csv_rank = {c: i for i, c in enumerate(csv_order)}
    violations = [(s, d) for s, d, *_ in EDGES if csv_rank[d] < csv_rank[s]]

    edges_out = []
    for src, dst, sign, strength, mech in EDGES:
        rho, n = spearman(num, src, dst)
        # An asserted direct effect whose *marginal* association points the other way.
        # Not an error: it is confounding, and it is the reason the generator needs the
        # graph rather than the correlation matrix.
        confounded = (
            rho is not None and abs(rho) > 0.03
            and ((sign == "+" and rho < 0) or (sign == "-" and rho > 0))
        )
        edges_out.append(dict(
            source=src, target=dst, sign=sign, strength=strength, mechanism=mech,
            rho=None if rho is None else round(rho, 3), n=n,
            sign_conflicts_marginal=confounded,
            csv_order_violation=csv_rank[dst] < csv_rank[src],
        ))

    missing_out = []
    for src, dst, sign, mech in MISSING_EDGES:
        missing_out.append(dict(source=src, target=dst, sign=sign, mechanism=mech))

    parents = {n["id"]: [] for n in NODES}
    for e in edges_out:
        parents[e["target"]].append(e["source"])

    # collider evidence for Lump Sum
    m = df.dropna(subset=["Non-Economic Loss", "Future Economic Loss"])
    a = np.log1p(m["Non-Economic Loss"]).to_numpy()
    b = np.log1p(m["Future Economic Loss"]).to_numpy()
    c = np.log(m["Lump Sum"]).to_numpy()

    def resid(v, z):
        X = np.column_stack([np.ones(len(z)), z])
        return v - X @ np.linalg.lstsq(X, v, rcond=None)[0]

    collider = dict(
        pair=["Non-Economic Loss", "Future Economic Loss"],
        collider="Lump Sum",
        n=int(len(m)),
        rho_marginal=round(float(stats.spearmanr(a, b).statistic), 3),
        rho_given_collider=round(float(stats.spearmanr(resid(a, c), resid(b, c)).statistic), 3),
    )

    doc = dict(
        name="nsw-ctp-severity",
        version="1.0",
        target="Lump Sum",
        n_rows=int(len(df)),
        description=(
            "DAG for NSW CTP impairment lump-sum awards, for DAG-aware autoregressive "
            "generation with TabPFN (Tugnoli et al., 2026). UNREVIEWED: edges, signs and "
            "mechanisms were generated by a large language model from NSW CTP scheme "
            "mechanics and claim chronology; no domain expert has reviewed them. The rho "
            "annotations are descriptive and do not validate any edge."
        ),
        provenance=dict(
            edge_source="llm_generated",
            model="Claude (Anthropic)",
            domain_review="none",
            reviewed_by=None,
            reviewed_at=None,
            basis="Motor Accident Injuries Act 2017 / Motor Accidents Compensation Act 1999 "
                  "heads of damage, as represented in the model's training data. No section-level "
                  "citations were recorded.",
            caveat="Treat every edge as a hypothesis pending review by a NSW CTP practitioner. "
                   "Descriptive statistics in the note/mechanism strings are verified by "
                   "causal/verify_claims.py; the causal assertions are not verifiable from this data.",
        ),
        bands=BANDS,
        nodes=NODES,
        edges=edges_out,
        parents=parents,
        topological_order=order,
        csv_column_order=csv_order,
        csv_order_violations=[list(v) for v in violations],
        missingness=dict(nodes=MISSING_NODES, edges=missing_out),
        colliders=[collider],
        categorical_contrasts={"Claimant Gender": "Male vs Female",
                               "Nature": "Damages vs Settlement Approval"},
        stats=dict(
            n_nodes=len(NODES), n_edges=len(EDGES),
            n_violations=len(violations),
            n_sign_conflicts=sum(e["sign_conflicts_marginal"] for e in edges_out),
            missing_rates={c: round(float(df[c].isna().mean()), 4)
                           for c in df.columns if df[c].isna().any()},
        ),
    )
    OUT.write_text(json.dumps(doc, indent=2), encoding="utf-8")

    print(f"wrote {OUT}")
    print(f"nodes={len(NODES)} edges={len(EDGES)} "
          f"csv-order violations={len(violations)}/{len(EDGES)}")
    print("topological order:")
    for i, nid in enumerate(order):
        print(f"  {i:2d}. {nid}")
    print(f"collider check: rho(NEL,FEL)={collider['rho_marginal']} -> "
          f"{collider['rho_given_collider']} given Lump Sum")


if __name__ == "__main__":
    main()
